runtime: python27
service: default
threadsafe: true
api_version: 1

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
  - url: /
    secure: always
    redirect_http_response_code: 301
    static_files: public/index.html
    upload: public/*

  - url: /(.*)/
    secure: always
    redirect_http_response_code: 301
    static_files: public/\1/index.html
    upload: public/*

  - url: /
    static_dir: public/
