baseURL = "https://rajshrimohanks.me/"
defaultcontentlanguage = "en"
languagecode = "en"
theme = "coder"
title = "Rajshri Mohan K S"

canonifyurls = true
paginate = 20

# disqusShortname = "rajshrimohanks"

# googleAnalytics = "UA-100193328-1"
googleAnalytics = "G-DM23Q9EY0L"

pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "api" # https://xyproto.github.io/splash/docs/all.html

[markup.highlight]
style = "github-dark"

[params]
author = "Rajshri Mohan K S"
avatarurl = "img/me.jpg"
# gravatar = "rajshrimohanks@gmail.com"
description = "Programmer. Technology Architect."
footercontent = "I made this site so I could write stuff."
info = "DevOps & Technology Architect. @IQZ Systems"
keywords = "blog,developer,personal"

dateformat = "January 2, 2006"

favicon_16 = "/img/favicon-16x16.png"
favicon_32 = "/img/favicon-32x32.png"

hidecopyright = false
hidecredits = false
since = 2019

rtl = false

colorscheme = "auto"
enableTwemoji = true
maxSeeAlsoItems = 5

customCSS = ["css/custom.css"]
math = false

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

# https://giscus.app
[params.giscus]
category = "Announcements"
categoryID = "DIC_kwDOEVWlRM4CTnkJ"
emitMetadata = "0"
inputPosition = "bottom"
lang = "en"
loading = "lazy"
mapping = "pathname"
reactionsEnabled = "1"
repo = "rajshrimohanks/rajshrimohanks.me"
repoID = "MDEwOlJlcG9zaXRvcnkyOTA4MjU1NDA="
strict = "0"
term = ""
theme = "preferred_color_scheme"

# Social links
[[params.social]]
icon = "fa fa-github"
name = "Github"
url = "https://github.com/rajshrimohanks"
weight = 1
[[params.social]]
icon = "fa fa-twitter"
name = "Twitter"
url = "https://twitter.com/Ma5terVain"
weight = 2
[[params.social]]
icon = "fa fa-stack-overflow"
name = "StackOverflow"
url = "https://stackoverflow.com/users/4050218/rajshri-mohan-k-s"
weight = 3
[[params.social]]
icon = "fa fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/rajshrimohanks/"
weight = 4
[[params.social]]
icon = "fa fa-rss"
name = "RSS"
rel = "alternate"
type = "application/rss+xml"
url = "https://rajshrimohanks.me/index.xml"
weight = 5

# Menu links
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
name = "Gear"
url = "/gear/"
weight = 3
# [[menu.main]]
# name = "Zikki Japo Art"
# url = "/zikki-japo/"
# weight = 4
[[menu.main]]
name = "Bucket List"
url = "/bucket-list/"
weight = 4
