baseURL = "https://rajshrimohanks.me/"
title = "Rajshri Mohan K S"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw" # https://xyproto.github.io/splash/docs/all.html
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "rajshrimohanks"

[params]
    author = "Rajshri Mohan K S"
    info = "Programmer. Technology Architect."
    description = "Programmer. Technology Architect."
    keywords = "blog,developer,personal"
    avatarurl = "img/me.jpg"

    dateformat = "January 2, 2006"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "I made this site so I could write stuff."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = false
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/rajshrimohanks"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/rajshrimohanks"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow"
    weight = 3
    url = "https://stackoverflow.com/users/4050218/rajshri-mohan-k-s"
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook"
    weight = 4
    url = "https://www.facebook.com/rajshrimohanks"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 5
    url = "https://www.linkedin.com/in/rajshrimohanks/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
