baseURL = "https://rajshrimohanks.me/"
title = "Rajshri Mohan K S"

theme = "coder"

defaultcontentlanguage = "en"
languagecode = "en"

canonifyurls = true
paginate = 20

pygmentscodefences = true 
pygmentscodefencesguesssyntax = true 
pygmentsstyle = "api" # https://xyproto.github.io/splash/docs/all.html

disqusShortname = "rajshrimohanks"

googleAnalytics = "UA-100193328-1"

[params]
author = "Rajshri Mohan K S"
avatarurl = "img/me.jpg"
# gravatar = "rajshrimohanks@gmail.com"
description = "Programmer. Technology Architect."
footercontent = "I made this site so I could write stuff."
info = "Programmer. DevOps & Technology Architect."
keywords = "blog,developer,personal"

dateformat = "January 2, 2006"

favicon_16 = "/img/favicon-16x16.png"
favicon_32 = "/img/favicon-32x32.png"

hidecopyright = false
hidecredits = false
since = 2019

rtl = false

colorscheme = "light"
maxSeeAlsoItems = 5

custom_css = ["css/custom.css"]
math = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

# Social links
[[params.social]]
icon = "fab fa-github"
name = "Github"
url = "https://github.com/rajshrimohanks"
weight = 1
[[params.social]]
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/Ma5terVain"
weight = 2
[[params.social]]
icon = "fab fa-stack-overflow"
name = "StackOverflow"
url = "https://stackoverflow.com/users/4050218/rajshri-mohan-k-s"
weight = 3
[[params.social]]
icon = "fab fa-facebook"
name = "Facebook"
url = "https://www.facebook.com/rajshrimohanks"
weight = 4
[[params.social]]
icon = "fab fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/rajshrimohanks/"
weight = 5
[[params.social]]
icon = "fas fa-rss"
name = "RSS"
rel = "alternate"
type = "application/rss+xml"
url = "https://rajshrimohanks.me/index.xml"
weight = 6

# Menu links
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 2
