name: Build and Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.136.2"
          extended: true

      - name: Build
        run: hugo --minify

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/739544187904/locations/global/workloadIdentityPools/rajshrimohanks-personal-pool/providers/rajshrimohanks-personal-provider"
          service_account: "rajshrimohanks-me-github-actio@rajshrimohanks-personal-page.iam.gserviceaccount.com"

      # Deploy App to App Engine
      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v2"
        with:
          flags: "--no-cache"


      - run: "gcloud app deploy dispatch.yaml --project rajshrimohanks-personal-page"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.GOOGLE_APPLICATION_CREDENTIALS }}
